// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLtiKELkkQUCmYjzzlospW4z9SrcpHO1A',
    appId: '1:1020915592761:web:37d6deec96613c702de7e8',
    messagingSenderId: '1020915592761',
    projectId: 'rdp-todo-7b1e9',
    authDomain: 'rdp-todo-7b1e9.firebaseapp.com',
    storageBucket: 'rdp-todo-7b1e9.firebasestorage.app',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy4_YaPQE-5HDS-wD2uIQxnmbOw_hzG8A',
    appId: '1:1020915592761:android:32545d533c8bb5a92de7e8',
    messagingSenderId: '1020915592761',
    projectId: 'rdp-todo-7b1e9',
    storageBucket: 'rdp-todo-7b1e9.firebasestorage.app',
  );
}
